export const FETCH_UPCOMING_MOVIES = 'FETCHING_UPCOMING_MOVIES';
export const FETCH_UPCOMING_SUCCESS = 'FETCH_UPCOMING_SUCCESS';
export const FETCH_UPCOMING_FAILURE = 'FETCH_UPCOMING_FAILURE';

export const FETCH_POPULAR_MOVIES = 'FETCHING_POPULAR_MOVIES';
export const FETCH_POPULAR_SUCCESS = 'FETCH_POPULAR_SUCCESS';
export const FETCH_POPULAR_FAILURE = 'FETCH_POPULAR_FAILURE';

export const FETCH_TOP_RATED_MOVIES = 'FETCH_TOP_RATED_MOVIES';
export const FETCH_TOP_RATED_SUCCESS = 'FETCH_TOP_RATED_SUCCESS';
export const FETCH_TOP_RATED_FAILURE = 'FETCH_TOP_RATED_FAILURE';

export const FETCH_MOVEI_CAST = 'FETCH_MOVEI_CAST';
export const FETCH_MOVEI_CAST_SUCCESS = 'FETCH_MOVEI_CAST_SUCCESS';
export const FETCH_MOVEI_CAST_FAILURE = 'FETCH_MOVEI_CAST_FAILURE';

export const FETCH_GENRES = 'FETCH_MOVEI_CAST';
export const FETCH_GENRES_SUCCESS = 'FETCH_MOVEI_CAST_SUCCESS';
export const FETCH_GENRES_FAILURE = 'FETCH_MOVEI_CAST_FAILURE';
